---
abstract: 'Zilla your distributions like RSRCHBOY!'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-RSRCHBOY
requires:
  Archive::Tar::Wrapper: 0
  Dist::Zilla: 0
  Dist::Zilla::Plugin::ArchiveRelease: 0
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::ConsistentVersionTest: 0
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::GitHub::Meta: 0
  Dist::Zilla::Plugin::GitHub::Update: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::InstallRelease: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::NoSmartCommentsTests: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Prepender: 0
  Dist::Zilla::Plugin::PruneFiles: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ReportVersions::Tiny: 0
  Dist::Zilla::Plugin::SurgicalPkgVersion: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::PodSpelling: 2.002001
  Dist::Zilla::Plugin::Test::Portability: 0
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::PluginBundle::Git::CheckFor: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  MooseX::AttributeShortcuts: 0
  Path::Class: 0
  Pod::Coverage::TrustPod: 0
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::Encoding: 0
  Pod::Weaver::Section::SeeAlso: 0
  Pod::Weaver::Section::SourceGitHub: 0
  Test::NoSmartComments: 0
  Test::Pod: 0
  Test::Pod::Content: 0
  Test::Pod::Coverage: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/RsrchBoy/Dist-Zilla-PluginBundle-RSRCHBOY/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-RSRCHBOY/
  repository: git://github.com/RsrchBoy/Dist-Zilla-PluginBundle-RSRCHBOY.git
version: 0.020
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RSRCHBOY/NextRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RSRCHBOY/@Git/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RSRCHBOY/@Git/Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RSRCHBOY/@Git/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RSRCHBOY/@Git/Push'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RSRCHBOY/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::CorrectBranch'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::Fixups
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::Fixups'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RSRCHBOY/GatherDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RSRCHBOY/PruneCruft'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::License
      name: '@RSRCHBOY/License'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RSRCHBOY/ExecDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RSRCHBOY/ShareDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RSRCHBOY/MakeMaker'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@RSRCHBOY/InstallGuide'
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RSRCHBOY/Manifest'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::SurgicalPkgVersion
      name: '@RSRCHBOY/SurgicalPkgVersion'
      version: 0.0019
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@RSRCHBOY/ReadmeFromPod'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RSRCHBOY/AutoPrereqs'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@RSRCHBOY/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@RSRCHBOY/Test::PodSpelling'
      version: 2.002004
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@RSRCHBOY/ConsistentVersionTest'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@RSRCHBOY/PodCoverageTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RSRCHBOY/PodSyntaxTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@RSRCHBOY/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@RSRCHBOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@RSRCHBOY/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@RSRCHBOY/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@RSRCHBOY/Test::Portability'
      version: 2.0.2
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@RSRCHBOY/ExtraTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@RSRCHBOY/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@RSRCHBOY/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::NoSmartCommentsTests
      name: '@RSRCHBOY/NoSmartCommentsTests'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RSRCHBOY/MetaConfig'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RSRCHBOY/MetaJSON'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RSRCHBOY/MetaYAML'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RSRCHBOY/TestRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RSRCHBOY/CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RSRCHBOY/ConfirmRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RSRCHBOY/UploadToCPAN'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@RSRCHBOY/GitHub::Meta'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@RSRCHBOY/GitHub::Update'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RSRCHBOY/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@RSRCHBOY/ReadmePodInRoot'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@RSRCHBOY/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@RSRCHBOY/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300015
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300015
