---
abstract: 'Zilla your Dists like RSRCHBOY!'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-RSRCHBOY
requires:
  Archive::Tar::Wrapper: 0
  Dist::Zilla: 0
  Dist::Zilla::Plugin::ArchiveRelease: 0
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::ConsistentVersionTest: 0
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::GitHub::Meta: 0
  Dist::Zilla::Plugin::GitHub::Update: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::InstallRelease: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::NoSmartCommentsTests: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Prepender: 0
  Dist::Zilla::Plugin::PruneFiles: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ReportVersions::Tiny: 0
  Dist::Zilla::Plugin::SurgicalPkgVersion: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::Portability: 0
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  MooseX::AttributeShortcuts: 0
  Pod::Coverage::TrustPod: 0
  Test::NoSmartComments: 0
  Test::Pod: 0
  Test::Pod::Content: 0
  Test::Pod::Coverage: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/RsrchBoy/Dist-Zilla-PluginBundle-RSRCHBOY/issues
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-RSRCHBOY/
  repository: git://github.com/RsrchBoy/Dist-Zilla-PluginBundle-RSRCHBOY.git
version: 0.012
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.113560
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.113560
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.113560
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.113560
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.113560
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: NoTabsTests
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: HasVersionTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: Test::Portability
      version: 2.0.2
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.03
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: ArchiveRelease
      version: 4.00
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.007
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: GitHub::Meta
      version: 0.14
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: GitHub::Update
      version: 0.14
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmePodInRoot
      version: 0.120052
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300006
